### ISSUE TITLE
Takes a lot of time to error out if port is not open

### ISSUE THREAD

**Issue by tsale** [audibleblink/bothan#1]
Hi,

Thank you for creating this tool, it is great. It takes a lot of time to error out when the port you are trying to scan is not open anymore. Is it possible to provide a fix for this?

Apologies for not proposing a solution, my knowledge on go is very primitive.

Thank you

**Comment by audibleblink** [comment]
Thanks. I'll take a look into a timeout function

**Comment by audibleblink** [comment]
@tsale  sorry it took so long for such an easy fix 8c8651158b462689855b81a29cd92fc05975e71f

**Comment by tsale** [comment]
Hey @audibleblink , not a problem. Thanks for fixing this :)
